### ISSUE TITLE
Separate/Combine - align index policy between UI and runtime (runtime:zero-based, UI:one-based)

### ISSUE THREAD

**Issue by nicolaferraro** [atlasmap/atlasmap-runtime#227]
I've used the twitter-to-salesforce demo and mapped the twitter screen name to firstName (index=1) and lastName (index=2) of the salesforce contact.

Happens that a guy with a single-worded name mentioned me on twitter and I got a IndexOutOfBounds exception.
I think the mapping should default to null when an index is not present, or the ui should provide a "skip if missing" flag.

**Comment by igarashitm** [comment]
Hi @nicolaferraro , can you paste the stacktrace here? I'm having a trouble reproducing it...

**Comment by igarashitm** [comment]
never mind, managed to reproduce

**Comment by igarashitm** [comment]
Sorry to hijack, but it reveals that the problem has more impacts. Right now runtime processes Combine/Separate mapping with zero-based indexing, while UI runs with one-based indexing. i.e. you always get index+1 element than you expect. This IOOBE also comes from this mismatch as an edge case. I think runtime should align with one-based indexing so that the mapping file also reflects what UI shows.
